-- =====================================================================
-- PRODE MUNDIAL 2026 - Club San Martin
-- Grupos y fixture REALES del sorteo 2026. Horarios de Buenos Aires.
-- Reemplaza los equipos y partidos cargados antes.
-- OJO: borra partidos y predicciones existentes. Correr ANTES de que
--      la gente empiece a pronosticar en serio.
-- Pegar en Supabase -> SQL Editor -> Run
-- =====================================================================

delete from public.matches;
delete from public.teams;

insert into public.teams (name, code, flag_url, group_letter) values
  ('México', 'MEX', 'https://flagcdn.com/w80/mx.png', 'A'),
  ('Sudáfrica', 'RSA', 'https://flagcdn.com/w80/za.png', 'A'),
  ('Corea del Sur', 'KOR', 'https://flagcdn.com/w80/kr.png', 'A'),
  ('Chequia', 'CZE', 'https://flagcdn.com/w80/cz.png', 'A'),
  ('Canadá', 'CAN', 'https://flagcdn.com/w80/ca.png', 'B'),
  ('Bosnia y Herzegovina', 'BIH', 'https://flagcdn.com/w80/ba.png', 'B'),
  ('Catar', 'QAT', 'https://flagcdn.com/w80/qa.png', 'B'),
  ('Suiza', 'SUI', 'https://flagcdn.com/w80/ch.png', 'B'),
  ('Brasil', 'BRA', 'https://flagcdn.com/w80/br.png', 'C'),
  ('Marruecos', 'MAR', 'https://flagcdn.com/w80/ma.png', 'C'),
  ('Haití', 'HAI', 'https://flagcdn.com/w80/ht.png', 'C'),
  ('Escocia', 'SCO', 'https://flagcdn.com/w80/gb-sct.png', 'C'),
  ('Estados Unidos', 'USA', 'https://flagcdn.com/w80/us.png', 'D'),
  ('Paraguay', 'PAR', 'https://flagcdn.com/w80/py.png', 'D'),
  ('Australia', 'AUS', 'https://flagcdn.com/w80/au.png', 'D'),
  ('Turquía', 'TUR', 'https://flagcdn.com/w80/tr.png', 'D'),
  ('Alemania', 'GER', 'https://flagcdn.com/w80/de.png', 'E'),
  ('Curazao', 'CUW', 'https://flagcdn.com/w80/cw.png', 'E'),
  ('Costa de Marfil', 'CIV', 'https://flagcdn.com/w80/ci.png', 'E'),
  ('Ecuador', 'ECU', 'https://flagcdn.com/w80/ec.png', 'E'),
  ('Países Bajos', 'NED', 'https://flagcdn.com/w80/nl.png', 'F'),
  ('Japón', 'JPN', 'https://flagcdn.com/w80/jp.png', 'F'),
  ('Suecia', 'SWE', 'https://flagcdn.com/w80/se.png', 'F'),
  ('Túnez', 'TUN', 'https://flagcdn.com/w80/tn.png', 'F'),
  ('Bélgica', 'BEL', 'https://flagcdn.com/w80/be.png', 'G'),
  ('Egipto', 'EGY', 'https://flagcdn.com/w80/eg.png', 'G'),
  ('Irán', 'IRN', 'https://flagcdn.com/w80/ir.png', 'G'),
  ('Nueva Zelanda', 'NZL', 'https://flagcdn.com/w80/nz.png', 'G'),
  ('España', 'ESP', 'https://flagcdn.com/w80/es.png', 'H'),
  ('Cabo Verde', 'CPV', 'https://flagcdn.com/w80/cv.png', 'H'),
  ('Arabia Saudita', 'KSA', 'https://flagcdn.com/w80/sa.png', 'H'),
  ('Uruguay', 'URU', 'https://flagcdn.com/w80/uy.png', 'H'),
  ('Francia', 'FRA', 'https://flagcdn.com/w80/fr.png', 'I'),
  ('Senegal', 'SEN', 'https://flagcdn.com/w80/sn.png', 'I'),
  ('Irak', 'IRQ', 'https://flagcdn.com/w80/iq.png', 'I'),
  ('Noruega', 'NOR', 'https://flagcdn.com/w80/no.png', 'I'),
  ('Argentina', 'ARG', 'https://flagcdn.com/w80/ar.png', 'J'),
  ('Argelia', 'ALG', 'https://flagcdn.com/w80/dz.png', 'J'),
  ('Austria', 'AUT', 'https://flagcdn.com/w80/at.png', 'J'),
  ('Jordania', 'JOR', 'https://flagcdn.com/w80/jo.png', 'J'),
  ('Portugal', 'POR', 'https://flagcdn.com/w80/pt.png', 'K'),
  ('RD Congo', 'COD', 'https://flagcdn.com/w80/cd.png', 'K'),
  ('Uzbekistán', 'UZB', 'https://flagcdn.com/w80/uz.png', 'K'),
  ('Colombia', 'COL', 'https://flagcdn.com/w80/co.png', 'K'),
  ('Inglaterra', 'ENG', 'https://flagcdn.com/w80/gb-eng.png', 'L'),
  ('Croacia', 'CRO', 'https://flagcdn.com/w80/hr.png', 'L'),
  ('Ghana', 'GHA', 'https://flagcdn.com/w80/gh.png', 'L'),
  ('Panamá', 'PAN', 'https://flagcdn.com/w80/pa.png', 'L');

insert into public.matches (home_team_id, away_team_id, match_date, stage, group_letter)
values
  ((select id from public.teams where code='MEX'), (select id from public.teams where code='RSA'), '2026-06-11 16:00:00-03', 'group', 'A'),
  ((select id from public.teams where code='KOR'), (select id from public.teams where code='CZE'), '2026-06-11 23:00:00-03', 'group', 'A'),
  ((select id from public.teams where code='CAN'), (select id from public.teams where code='BIH'), '2026-06-12 16:00:00-03', 'group', 'B'),
  ((select id from public.teams where code='USA'), (select id from public.teams where code='PAR'), '2026-06-12 22:00:00-03', 'group', 'D'),
  ((select id from public.teams where code='QAT'), (select id from public.teams where code='SUI'), '2026-06-13 16:00:00-03', 'group', 'B'),
  ((select id from public.teams where code='BRA'), (select id from public.teams where code='MAR'), '2026-06-13 19:00:00-03', 'group', 'C'),
  ((select id from public.teams where code='HAI'), (select id from public.teams where code='SCO'), '2026-06-13 22:00:00-03', 'group', 'C'),
  ((select id from public.teams where code='AUS'), (select id from public.teams where code='TUR'), '2026-06-14 01:00:00-03', 'group', 'D'),
  ((select id from public.teams where code='GER'), (select id from public.teams where code='CUW'), '2026-06-14 14:00:00-03', 'group', 'E'),
  ((select id from public.teams where code='NED'), (select id from public.teams where code='JPN'), '2026-06-14 17:00:00-03', 'group', 'F'),
  ((select id from public.teams where code='CIV'), (select id from public.teams where code='ECU'), '2026-06-14 20:00:00-03', 'group', 'E'),
  ((select id from public.teams where code='SWE'), (select id from public.teams where code='TUN'), '2026-06-14 23:00:00-03', 'group', 'F'),
  ((select id from public.teams where code='ESP'), (select id from public.teams where code='CPV'), '2026-06-15 13:00:00-03', 'group', 'H'),
  ((select id from public.teams where code='BEL'), (select id from public.teams where code='EGY'), '2026-06-15 16:00:00-03', 'group', 'G'),
  ((select id from public.teams where code='KSA'), (select id from public.teams where code='URU'), '2026-06-15 19:00:00-03', 'group', 'H'),
  ((select id from public.teams where code='IRN'), (select id from public.teams where code='NZL'), '2026-06-15 22:00:00-03', 'group', 'G'),
  ((select id from public.teams where code='FRA'), (select id from public.teams where code='SEN'), '2026-06-16 16:00:00-03', 'group', 'I'),
  ((select id from public.teams where code='IRQ'), (select id from public.teams where code='NOR'), '2026-06-16 19:00:00-03', 'group', 'I'),
  ((select id from public.teams where code='ARG'), (select id from public.teams where code='ALG'), '2026-06-16 22:00:00-03', 'group', 'J'),
  ((select id from public.teams where code='AUT'), (select id from public.teams where code='JOR'), '2026-06-17 01:00:00-03', 'group', 'J'),
  ((select id from public.teams where code='POR'), (select id from public.teams where code='COD'), '2026-06-17 14:00:00-03', 'group', 'K'),
  ((select id from public.teams where code='ENG'), (select id from public.teams where code='CRO'), '2026-06-17 17:00:00-03', 'group', 'L'),
  ((select id from public.teams where code='GHA'), (select id from public.teams where code='PAN'), '2026-06-17 20:00:00-03', 'group', 'L'),
  ((select id from public.teams where code='UZB'), (select id from public.teams where code='COL'), '2026-06-17 23:00:00-03', 'group', 'K'),
  ((select id from public.teams where code='CZE'), (select id from public.teams where code='RSA'), '2026-06-18 13:00:00-03', 'group', 'A'),
  ((select id from public.teams where code='SUI'), (select id from public.teams where code='BIH'), '2026-06-18 16:00:00-03', 'group', 'B'),
  ((select id from public.teams where code='CAN'), (select id from public.teams where code='QAT'), '2026-06-18 19:00:00-03', 'group', 'B'),
  ((select id from public.teams where code='MEX'), (select id from public.teams where code='KOR'), '2026-06-18 22:00:00-03', 'group', 'A'),
  ((select id from public.teams where code='USA'), (select id from public.teams where code='AUS'), '2026-06-19 16:00:00-03', 'group', 'D'),
  ((select id from public.teams where code='SCO'), (select id from public.teams where code='MAR'), '2026-06-19 19:00:00-03', 'group', 'C'),
  ((select id from public.teams where code='BRA'), (select id from public.teams where code='HAI'), '2026-06-19 21:30:00-03', 'group', 'C'),
  ((select id from public.teams where code='TUR'), (select id from public.teams where code='PAR'), '2026-06-20 00:00:00-03', 'group', 'D'),
  ((select id from public.teams where code='NED'), (select id from public.teams where code='SWE'), '2026-06-20 14:00:00-03', 'group', 'F'),
  ((select id from public.teams where code='GER'), (select id from public.teams where code='CIV'), '2026-06-20 17:00:00-03', 'group', 'E'),
  ((select id from public.teams where code='ECU'), (select id from public.teams where code='CUW'), '2026-06-20 21:00:00-03', 'group', 'E'),
  ((select id from public.teams where code='TUN'), (select id from public.teams where code='JPN'), '2026-06-21 01:00:00-03', 'group', 'F'),
  ((select id from public.teams where code='ESP'), (select id from public.teams where code='KSA'), '2026-06-21 13:00:00-03', 'group', 'H'),
  ((select id from public.teams where code='BEL'), (select id from public.teams where code='IRN'), '2026-06-21 16:00:00-03', 'group', 'G'),
  ((select id from public.teams where code='URU'), (select id from public.teams where code='CPV'), '2026-06-21 19:00:00-03', 'group', 'H'),
  ((select id from public.teams where code='NZL'), (select id from public.teams where code='EGY'), '2026-06-21 22:00:00-03', 'group', 'G'),
  ((select id from public.teams where code='ARG'), (select id from public.teams where code='AUT'), '2026-06-22 14:00:00-03', 'group', 'J'),
  ((select id from public.teams where code='FRA'), (select id from public.teams where code='IRQ'), '2026-06-22 18:00:00-03', 'group', 'I'),
  ((select id from public.teams where code='NOR'), (select id from public.teams where code='SEN'), '2026-06-22 21:00:00-03', 'group', 'I'),
  ((select id from public.teams where code='JOR'), (select id from public.teams where code='ALG'), '2026-06-23 00:00:00-03', 'group', 'J'),
  ((select id from public.teams where code='POR'), (select id from public.teams where code='UZB'), '2026-06-23 14:00:00-03', 'group', 'K'),
  ((select id from public.teams where code='ENG'), (select id from public.teams where code='GHA'), '2026-06-23 17:00:00-03', 'group', 'L'),
  ((select id from public.teams where code='PAN'), (select id from public.teams where code='CRO'), '2026-06-23 20:00:00-03', 'group', 'L'),
  ((select id from public.teams where code='COL'), (select id from public.teams where code='COD'), '2026-06-23 23:00:00-03', 'group', 'K'),
  ((select id from public.teams where code='SUI'), (select id from public.teams where code='CAN'), '2026-06-24 16:00:00-03', 'group', 'B'),
  ((select id from public.teams where code='BIH'), (select id from public.teams where code='QAT'), '2026-06-24 16:00:00-03', 'group', 'B'),
  ((select id from public.teams where code='MAR'), (select id from public.teams where code='HAI'), '2026-06-24 19:00:00-03', 'group', 'C'),
  ((select id from public.teams where code='SCO'), (select id from public.teams where code='BRA'), '2026-06-24 19:00:00-03', 'group', 'C'),
  ((select id from public.teams where code='RSA'), (select id from public.teams where code='KOR'), '2026-06-24 22:00:00-03', 'group', 'A'),
  ((select id from public.teams where code='CZE'), (select id from public.teams where code='MEX'), '2026-06-24 22:00:00-03', 'group', 'A'),
  ((select id from public.teams where code='CUW'), (select id from public.teams where code='CIV'), '2026-06-25 17:00:00-03', 'group', 'E'),
  ((select id from public.teams where code='ECU'), (select id from public.teams where code='GER'), '2026-06-25 17:00:00-03', 'group', 'E'),
  ((select id from public.teams where code='TUN'), (select id from public.teams where code='NED'), '2026-06-25 20:00:00-03', 'group', 'F'),
  ((select id from public.teams where code='JPN'), (select id from public.teams where code='SWE'), '2026-06-25 20:00:00-03', 'group', 'F'),
  ((select id from public.teams where code='TUR'), (select id from public.teams where code='USA'), '2026-06-25 23:00:00-03', 'group', 'D'),
  ((select id from public.teams where code='PAR'), (select id from public.teams where code='AUS'), '2026-06-25 23:00:00-03', 'group', 'D'),
  ((select id from public.teams where code='NOR'), (select id from public.teams where code='FRA'), '2026-06-26 16:00:00-03', 'group', 'I'),
  ((select id from public.teams where code='SEN'), (select id from public.teams where code='IRQ'), '2026-06-26 16:00:00-03', 'group', 'I'),
  ((select id from public.teams where code='CPV'), (select id from public.teams where code='KSA'), '2026-06-26 21:00:00-03', 'group', 'H'),
  ((select id from public.teams where code='URU'), (select id from public.teams where code='ESP'), '2026-06-26 21:00:00-03', 'group', 'H'),
  ((select id from public.teams where code='NZL'), (select id from public.teams where code='BEL'), '2026-06-27 00:00:00-03', 'group', 'G'),
  ((select id from public.teams where code='EGY'), (select id from public.teams where code='IRN'), '2026-06-27 00:00:00-03', 'group', 'G'),
  ((select id from public.teams where code='PAN'), (select id from public.teams where code='ENG'), '2026-06-27 18:00:00-03', 'group', 'L'),
  ((select id from public.teams where code='CRO'), (select id from public.teams where code='GHA'), '2026-06-27 18:00:00-03', 'group', 'L'),
  ((select id from public.teams where code='COL'), (select id from public.teams where code='POR'), '2026-06-27 20:30:00-03', 'group', 'K'),
  ((select id from public.teams where code='COD'), (select id from public.teams where code='UZB'), '2026-06-27 20:30:00-03', 'group', 'K'),
  ((select id from public.teams where code='ALG'), (select id from public.teams where code='AUT'), '2026-06-27 23:00:00-03', 'group', 'J'),
  ((select id from public.teams where code='JOR'), (select id from public.teams where code='ARG'), '2026-06-27 23:00:00-03', 'group', 'J');
