-- =====================================================================
-- PRODE MUNDIAL 2026 - Club San Martin
-- Setup completo de Supabase (idempotente: se puede correr varias veces)
-- Pegar TODO esto en Supabase -> SQL Editor -> Run
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1) TABLAS
-- ---------------------------------------------------------------------

create table if not exists public.teams (
  id           bigint generated by default as identity primary key,
  name         text not null,
  code         text not null unique,
  flag_url     text,
  group_letter text
);

create table if not exists public.profiles (
  id         uuid primary key references auth.users(id) on delete cascade,
  email      text not null,
  full_name  text,
  is_admin   boolean not null default false,
  points     integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.matches (
  id           bigint generated by default as identity primary key,
  home_team_id bigint not null references public.teams(id) on delete cascade,
  away_team_id bigint not null references public.teams(id) on delete cascade,
  home_score   integer,
  away_score   integer,
  match_date   timestamptz,
  stage        text not null default 'group',
  group_letter text,
  is_finished  boolean not null default false,
  created_at   timestamptz not null default now()
);

create table if not exists public.predictions (
  id            bigint generated by default as identity primary key,
  user_id       uuid not null references public.profiles(id) on delete cascade,
  match_id      bigint not null references public.matches(id) on delete cascade,
  home_score    integer not null,
  away_score    integer not null,
  points_earned integer not null default 0,
  created_at    timestamptz not null default now(),
  unique (user_id, match_id)
);

-- ---------------------------------------------------------------------
-- 2) FUNCIONES
-- ---------------------------------------------------------------------

-- Crea el perfil automaticamente cuando se registra un usuario nuevo,
-- tomando el nombre que se manda en el signup (options.data.full_name).
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, full_name)
  values (new.id, new.email, new.raw_user_meta_data->>'full_name')
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- Chequea si un usuario es admin (security definer: evita recursion con RLS).
create or replace function public.is_admin(uid uuid)
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select coalesce((select is_admin from public.profiles where id = uid), false);
$$;

-- Suma puntos al total de un usuario. La llama el panel de admin al cargar
-- un resultado: supabase.rpc('increment_points', { user_id, points_to_add }).
create or replace function public.increment_points(user_id uuid, points_to_add integer)
returns void
language sql
security definer
set search_path = public
as $$
  update public.profiles
  set points = points + points_to_add
  where id = user_id;
$$;

-- ---------------------------------------------------------------------
-- 3) ROW LEVEL SECURITY (RLS)
-- ---------------------------------------------------------------------

alter table public.teams       enable row level security;
alter table public.profiles    enable row level security;
alter table public.matches     enable row level security;
alter table public.predictions enable row level security;

-- TEAMS: cualquiera puede ver (la landing los muestra sin login); solo admin escribe.
drop policy if exists "teams_select_all" on public.teams;
create policy "teams_select_all" on public.teams
  for select using (true);

drop policy if exists "teams_admin_write" on public.teams;
create policy "teams_admin_write" on public.teams
  for all using (public.is_admin(auth.uid())) with check (public.is_admin(auth.uid()));

-- MATCHES: cualquiera puede ver; solo admin crea/edita.
drop policy if exists "matches_select_all" on public.matches;
create policy "matches_select_all" on public.matches
  for select using (true);

drop policy if exists "matches_admin_write" on public.matches;
create policy "matches_admin_write" on public.matches
  for all using (public.is_admin(auth.uid())) with check (public.is_admin(auth.uid()));

-- PROFILES: usuarios logueados ven todos (ranking); cada uno edita el suyo; admin edita cualquiera.
drop policy if exists "profiles_select_auth" on public.profiles;
create policy "profiles_select_auth" on public.profiles
  for select using (auth.role() = 'authenticated');

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own" on public.profiles
  for update using (auth.uid() = id) with check (auth.uid() = id);

drop policy if exists "profiles_update_admin" on public.profiles;
create policy "profiles_update_admin" on public.profiles
  for update using (public.is_admin(auth.uid())) with check (public.is_admin(auth.uid()));

-- PREDICTIONS: cada uno maneja las suyas; admin ve todas (para calcular puntos).
drop policy if exists "predictions_select_own" on public.predictions;
create policy "predictions_select_own" on public.predictions
  for select using (auth.uid() = user_id or public.is_admin(auth.uid()));

drop policy if exists "predictions_insert_own" on public.predictions;
create policy "predictions_insert_own" on public.predictions
  for insert with check (auth.uid() = user_id);

drop policy if exists "predictions_update_own" on public.predictions;
create policy "predictions_update_own" on public.predictions
  for update using (auth.uid() = user_id or public.is_admin(auth.uid()))
  with check (auth.uid() = user_id or public.is_admin(auth.uid()));

-- ---------------------------------------------------------------------
-- 4) SEED: 48 selecciones con banderas (flagcdn.com)
-- ---------------------------------------------------------------------

insert into public.teams (name, code, flag_url, group_letter) values
  ('México',          'MEX', 'https://flagcdn.com/w80/mx.png',     'A'),
  ('Canadá',          'CAN', 'https://flagcdn.com/w80/ca.png',     'A'),
  ('Ecuador',         'ECU', 'https://flagcdn.com/w80/ec.png',     'A'),
  ('Venezuela',       'VEN', 'https://flagcdn.com/w80/ve.png',     'A'),
  ('Estados Unidos',  'USA', 'https://flagcdn.com/w80/us.png',     'B'),
  ('Inglaterra',      'ENG', 'https://flagcdn.com/w80/gb-eng.png', 'B'),
  ('Irán',            'IRN', 'https://flagcdn.com/w80/ir.png',     'B'),
  ('Gales',           'WAL', 'https://flagcdn.com/w80/gb-wls.png', 'B'),
  ('Argentina',       'ARG', 'https://flagcdn.com/w80/ar.png',     'C'),
  ('Polonia',         'POL', 'https://flagcdn.com/w80/pl.png',     'C'),
  ('Arabia Saudita',  'KSA', 'https://flagcdn.com/w80/sa.png',     'C'),
  ('Australia',       'AUS', 'https://flagcdn.com/w80/au.png',     'C'),
  ('Francia',         'FRA', 'https://flagcdn.com/w80/fr.png',     'D'),
  ('Dinamarca',       'DEN', 'https://flagcdn.com/w80/dk.png',     'D'),
  ('Túnez',           'TUN', 'https://flagcdn.com/w80/tn.png',     'D'),
  ('Perú',            'PER', 'https://flagcdn.com/w80/pe.png',     'D'),
  ('España',          'ESP', 'https://flagcdn.com/w80/es.png',     'E'),
  ('Alemania',        'GER', 'https://flagcdn.com/w80/de.png',     'E'),
  ('Japón',           'JPN', 'https://flagcdn.com/w80/jp.png',     'E'),
  ('Costa Rica',      'CRC', 'https://flagcdn.com/w80/cr.png',     'E'),
  ('Bélgica',         'BEL', 'https://flagcdn.com/w80/be.png',     'F'),
  ('Croacia',         'CRO', 'https://flagcdn.com/w80/hr.png',     'F'),
  ('Marruecos',       'MAR', 'https://flagcdn.com/w80/ma.png',     'F'),
  ('Camerún',         'CMR', 'https://flagcdn.com/w80/cm.png',     'F'),
  ('Brasil',          'BRA', 'https://flagcdn.com/w80/br.png',     'G'),
  ('Suiza',           'SUI', 'https://flagcdn.com/w80/ch.png',     'G'),
  ('Serbia',          'SRB', 'https://flagcdn.com/w80/rs.png',     'G'),
  ('Nigeria',         'NGA', 'https://flagcdn.com/w80/ng.png',     'G'),
  ('Portugal',        'POR', 'https://flagcdn.com/w80/pt.png',     'H'),
  ('Uruguay',         'URU', 'https://flagcdn.com/w80/uy.png',     'H'),
  ('Corea del Sur',   'KOR', 'https://flagcdn.com/w80/kr.png',     'H'),
  ('Ghana',           'GHA', 'https://flagcdn.com/w80/gh.png',     'H'),
  ('Países Bajos',    'NED', 'https://flagcdn.com/w80/nl.png',     'I'),
  ('Senegal',         'SEN', 'https://flagcdn.com/w80/sn.png',     'I'),
  ('Qatar',           'QAT', 'https://flagcdn.com/w80/qa.png',     'I'),
  ('Jamaica',         'JAM', 'https://flagcdn.com/w80/jm.png',     'I'),
  ('Italia',          'ITA', 'https://flagcdn.com/w80/it.png',     'J'),
  ('Colombia',        'COL', 'https://flagcdn.com/w80/co.png',     'J'),
  ('Egipto',          'EGY', 'https://flagcdn.com/w80/eg.png',     'J'),
  ('Panamá',          'PAN', 'https://flagcdn.com/w80/pa.png',     'J'),
  ('Chile',           'CHI', 'https://flagcdn.com/w80/cl.png',     'K'),
  ('Paraguay',        'PAR', 'https://flagcdn.com/w80/py.png',     'K'),
  ('Argelia',         'ALG', 'https://flagcdn.com/w80/dz.png',     'K'),
  ('Nueva Zelanda',   'NZL', 'https://flagcdn.com/w80/nz.png',     'K'),
  ('Austria',         'AUT', 'https://flagcdn.com/w80/at.png',     'L'),
  ('Ucrania',         'UKR', 'https://flagcdn.com/w80/ua.png',     'L'),
  ('Honduras',        'HON', 'https://flagcdn.com/w80/hn.png',     'L'),
  ('Indonesia',       'IDN', 'https://flagcdn.com/w80/id.png',     'L')
on conflict (code) do update
  set name = excluded.name,
      flag_url = excluded.flag_url,
      group_letter = excluded.group_letter;

-- =====================================================================
-- LISTO. Para hacerte admin a vos: registrate primero en la app, despues
-- corre esto reemplazando tu email:
--
--   update public.profiles set is_admin = true where email = 'TU_EMAIL_ACA';
--
-- =====================================================================
